name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          tnieyustudyacc176/base-web-js:latest

  deploy:
  
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get raw URL of docker-compose.yml
        run: |
          DOCKER_COMPOSE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yaml"
          echo "DOCKER_COMPOSE_URL=$DOCKER_COMPOSE_URL" >> $GITHUB_ENV

      - name: SSH deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          envs: DOCKER_COMPOSE_URL
          script: |
            echo "DOCKER_COMPOSE_URL: ${DOCKER_COMPOSE_URL}"

            DOCKER_COMPOSE_PATH="/test-demo/docker-compose.yaml"

            sudo mkdir -p $(dirname $DOCKER_COMPOSE_PATH)
            sudo curl -o $DOCKER_COMPOSE_PATH ${DOCKER_COMPOSE_URL}

            echo "Logging in to Docker Hub"
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            cd $(dirname $DOCKER_COMPOSE_PATH)

            echo "Pulling latest app image"
            docker-compose pull app

            echo "Restarting app service"
            docker-compose up -d app

            echo "Cleanup unused images"
            docker image prune -f

            echo "Deployment successful!"

